# Generated by Django 4.1.4 on 2022-12-17 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PARCELSETTINGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalparceloutlinecolor', models.CharField(blank=True, max_length=150, null=True, verbose_name='GENERAL PARCEL OUTLINE COLOR')),
                ('generalparceloutlinewidth', models.IntegerField(blank=True, null=True, verbose_name='GENERAL PARCEL OUTLINE WIDTH')),
                ('generalparcelfillcolor', models.CharField(blank=True, max_length=150, null=True, verbose_name='GENERAL PARCEL FILL COLOR')),
                ('generalparcelfillcoloropacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GENERAL PARCEL FILL COLOR OPACITY')),
                ('selectedparceloutlinecolor', models.CharField(blank=True, max_length=150, null=True, verbose_name='SELECTED PARCEL OUTLINE COLOR')),
                ('selectedparceloutlinewidth', models.IntegerField(blank=True, null=True, verbose_name='SELECTED PARCEL OUTLINE WIDTH')),
                ('selectedparcelfillcolor', models.CharField(blank=True, max_length=150, null=True, verbose_name='SELECTED PARCEL FILL COLOR')),
                ('selectedparcelfillcoloropacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SELECTED PARCEL FILL COLOR OPACITY')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parcelssettings', to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
        ),
    ]
