# Generated by Django 4.1.4 on 2022-12-29 00:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_parcelsettings_created_parcelsettings_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PARCELSETTINGS',
            new_name='ParcelSetting',
        ),
        migrations.AlterModelOptions(
            name='parcelsetting',
            options={'verbose_name': 'PARCEL SETTING', 'verbose_name_plural': 'PARCEL SETTINGS'},
        ),
    ]
