# Generated by Django 4.1.4 on 2022-12-17 16:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcelboundarycenterWGS84',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326, verbose_name='PARCEL BOUNDARY CENTER WGS84'),
        ),
    ]
