# Generated by Django 4.1.4 on 2023-01-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countryboundaryCRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinatesystem_countries', to='parcels.coordinatesystem', verbose_name='BOUNDARY COORDINATE SYSTEM'),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtboundaryCRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinatesystem_districts', to='parcels.coordinatesystem', verbose_name='BOUNDARY COORDINATE SYSTEM'),
        ),
        migrations.AlterField(
            model_name='region',
            name='regionboundaryCRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinatesystem_regions', to='parcels.coordinatesystem', verbose_name='BOUNDARY COORDINATE SYSTEM'),
        ),
        migrations.AlterField(
            model_name='town',
            name='townboundaryCRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinatesystem_towns', to='parcels.coordinatesystem', verbose_name='BOUNDARY COORDINATE SYSTEM'),
        ),
    ]
