# Generated by Django 4.1.2 on 2022-11-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='registered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DATETIME REGISTERED'),
        ),
    ]
